/// Flutter icons Braille_hand
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Braille_hand
///      fonts:
///       - asset: fonts/Braille_hand.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Braille_hand {
  Braille_hand._();

  static const _kFontFam = 'Braille_hand';
  static const _kFontPkg = null;

  static const IconData braille_hand = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand_pointer_o = IconData(0xf25a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
